project:
  type: website
  resources:
    - CNAME
  output-dir: docs
  render:
    - "*.qmd"

website:
  title: "Jun Yan #Statistical Computing"
  search: false
  cookie-consent: false
  twitter-card: true
  open-graph: true
  site-url: https://statcomp-org.github.io
  navbar:
    right:
      - publications.qmd
      - teaching.qmd
      - students.qmd
      - software.qmd
      - misc.qmd
#      - icon: github
#        href: https://github.com/
page-footer: 
   left: "215 Glebbrook Rd. U-4120, Storrs, CT 06033 USA"

format:
  html:
    theme: cosmo
    css: styles.css
    default-image-extension: ""



