---
title: "Teaching"
---

## Open-Source Classnotes

+ STAT/DSDA 1010: Data Science and the Society with R
    - [Fall 2025](https://statds.github.io/1010f25)
+ STAT 3255/5255: Introduction to Data Science
    - [Fall 2025](https://statds.github.io/ids-f25)
    - [Spring 2025](https://statds.github.io/ids-s25)
        * Class presentation at 2025 NYC Open Data Week: [Risk Analysis of NYC Street Flood]( https://2025.open-data.nyc/event/risk-analysis-of-nyc-street-flooding/)
    - [Fall 2024](https://statds.github.io/ids-f24/)
    - [Spring 2024](https://statds.github.io/ids-s24/)
        * Class presentation at 2024 NYC Open Data Week: [Landscape of Rodent Sightings in New York City: A Data Science Showcase](https://youtu.be/ikPFSuhWvsg?si=eMj6nkScCgxKUmgt)
        <!-- * Data cleaning workshop at 2024 NYC Open Data Week: [Is your data really that dirty? An in-depth look at NYC 311 data to determine its “cleanliness”](https://youtu.be/YkTIEYh7UgM?si=auyNHzxjCu9ztl8u) -->
    - [Spring 2023](https://statds.github.io/ids-s23/)
        * Class presentation at 2023 NYC Open Data Week: [Data Science at UConn with NYC Open Data](https://youtu.be/YV_SC3SS8mg?si=ySKwb2h5WMmTZsb6)
    - [Spring 2022](https://statds.github.io/ids-s22/)
        * Class presentation at 2022 NYC Open Data Week: [NYC Open Data Case Studies from Introduction to Data Science at UConn](https://youtu.be/YV_SC3SS8mg?si=ySKwb2h5WMmTZsb6)
+ STAT 3494: [Statistical Writing](https://statds.github.io/stat-writing/)
+ STAT 5361: [Statistical Computing](https://jun-yan.github.io/stat-5361/)

## Undergraduate Advisee Publications

+ **Fiore, O.**, Schifano, E. D., and Yan, J. (2025+): On Devon
  Allen’s disqualification at the 2022 World Track and Field
  Championships. *The American Statistician*, forthcoming.
<https://doi.org/10.1080/00031305.2025.2515869>
+ **Zeimbekakis, A.**, Schifano, E. D., & Yan, J. (2024). On misuses of the
Kolmogorov--Smirnov test for one-sample goodness-of-fit. *The American
Statistician*, *78(4)*: 481–487.
<https://doi.org/10.1080/00031305.2024.2356095>
+ **Houlihan, K.** & Yan, J. (2024): How to build a gymnastics team.
*Significance*, *21(3)*, 10--14.
<https://doi.org/10.1093/jrssig/qmae039>
+ **Chandy, M.**, Schifano, E., & Yan, J. (2024): On sample size needed for block
bootstrap confidence intervals to have desired coverage rates.
*American Journal of Undergraduate Research*, *20(4)*, 3--16.
<https://doi.org/10.33697/ajur.2024.101>
[UConn Today story](https://today.uconn.edu/2024/04/mathew-chandy-24-college-of-liberal-arts-and-sciences/)
+ **Price, M.** & Yan, J. (2022). The effects of the NBA COVID bubble on the
NBA playoffs: A case study for home-court advantage. *American Journal
of Undergraduate Research*, *18(4)*, 3--15.
<https://doi.org/10.33697/ajur.2022.051>


## Student Awards
+  Zhenyu Xu (2025): Student Paper Award, 2025 Applied Statistics Symposium, International Chinese Statistical Association.
+ Sydney Louit (2025): Student Paper Award, Section on Physical and Engineering Sciences, American Statistical Association.
+ Jackson Lautier (2024): Honorable Mention, Arnold Zellner Thesis Award in Econometrics and Statistics, American Statistical Association.
+ Luis Sydney (2024): Honorable Mention, Student Paper Award, 2024 Applied Statistics Symposium, International Chinese Statistical Association.
+ Lucus Godoy (2024): Honoroble Mention, Student Paper Award, Section on Statistics and the Environment, Ameri can Statistical Association.
+ Yingfa Xie (2024): Student Paper Award, Section on Lifetime Data Science, American Statistical Association.
+ Zehan Yang (2023): Honorable Mention, Student Paper Award, 2023 Applied Statistics Symposium, International Chinese Statistical Association.
+ Yelie Yuan (2023): Honorable Mention, John M. Chambers Statistical Software Award, American Statistical Association.
+ Jackson Lautier (2022): Student Paper Award, Special Conference Celebrating the 60th Anniversary of UConn Department of Statistics.
+ Zehan Yang (2022): Student Paper Award, Section on Lifetime Data Science, American Statistical Association.
+ Jackson Lautier (2022): Student Paper Award, Risk Analysis Section, American Statistical Association.
+ Jun Jin (2022): Honorable Mention, Student Paper Award, Risk Analysis Section, American Statistical Association.
+ Chaoran Hu (2020): Student Paper Award, Statistical Computing and Statistical Graphics Sections, American Statistical Association.
+ Yan Li (2020): ENAR Distinguished Student Paper Award, International Biometric Society.
+ Yan Li (2019): IBM Student Paper Award, 33rd New England Statistics Symposium.
+ Yishu Xue (2019): ENAR Distinguished Student Paper Award, International Biometric Society.
+ Wenjie Wang (2017): IBM Student Paper Award, 31st New England Statistics Symposium.
+ Gregory Vaughan (2017): Student Paper Award, Mental Health Section, American Statistical Association.
+ Steven Chiou (2012): Student Paper Award, Applied Statistics Symposium, International Chinese Statistical Association.
+ Yung-wei Chen (2012): Student Paper Award, Social Statistics, Government Statistics, and Survey Research Methods Sections, American Statistical Association.
+ Xiaojing Wang (2010): IBM Student Paper Award, 24th New England Statistics Symposium.
